Repository hochan222/holyGraph, pull requests merged in 2020-05, with the labels that each got.

#7 [MODIFY] README.md 2020_05_10
  README.md
Labels: 개발

#15 [CREATE]: lib/boilerplate / CRA for graph boilerplate && README
  README.md
  lib/boilerplate/.gitignore
  lib/boilerplate/README.md
  lib/boilerplate/package.json
  lib/boilerplate/public/favicon.ico
  lib/boilerplate/public/index.html
  lib/boilerplate/public/logo192.png
  lib/boilerplate/public/logo512.png
  lib/boilerplate/public/manifest.json
  lib/boilerplate/public/robots.txt
  lib/boilerplate/src/App.css
  lib/boilerplate/src/App.js
  lib/boilerplate/src/App.test.js
  lib/boilerplate/src/index.css
  lib/boilerplate/src/index.js
  lib/boilerplate/src/serviceWorker.js
  lib/boilerplate/src/setupTests.js
  lib/boilerplate/yarn.lock
Labels: Graph, 개발

#17 [CREATE] gh-pages: https://hochan222.github.io/holyGraph/
  lib/boilerplate/package.json
  lib/boilerplate/yarn.lock
Labels: 개발 환경

#23 [FIX]LICENSE
  LICENSE
Labels: 기획

#24 [FIX] graph width height// app.css: height: 100vh && app.js options
  lib/boilerplate/src/App.css
  lib/boilerplate/src/App.js
  lib/boilerplate/src/index.css
Labels: Graph

#27 [CREATE] Node/Edges Data for Module && ADD
  lib/boilerplate/src/App.js
  lib/boilerplate/src/_data.js
Labels: Graph
